version: '3'

services:
  backend:
    build: ./backend/.
    ports:
      - "4567:4567"
    volumes:
      - ./backend/.:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/backend
volumes:
  gem_cache:
