version: '3'

services:
  web:
    build: .
    ports:
      - "4567:4567"
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    env_file:
      - .env/development/web
        
  sass:
    build: .
    volumes:
      - ./css:/usr/src/app/css
      - ./public:/usr/src/app/public
    command: "npm run scss"

volumes:
  gem_cache:
